# -*- coding: utf-8 -*-
"""Final_Group_Project_3_IT_BOOTCAMP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyI0y5kY4RtQ8vJsahn6YcfnkVDHcmJY

# Business Understanding

This dataset aims to identify the key factors that influence students' examination scores. By understanding these patterns, schools and educational policymakers can make more informed decisions, such as providing additional academic support to specific groups of students, improving access to test preparation programs, and adapting teaching strategies based on students' characteristics.

# Data Understanding

The Exam dataset contains **1,000 records** and **8 features**. The variables included in the dataset are:

- **Gender:** Student's gender (Male/Female).
- **Race/Ethnicity:** Student's race or ethnicity group.
- **Parental Level of Education:** Highest educational qualification of the student's parents.
- **Lunch:** Type of lunch received by the student (Standard or Free/Reduced).
- **Test Preparation Course:** Completion status of the test preparation course (Completed/None).
- **Mathematics Score:** Student's Mathematics examination score.
- **Reading Score:** Student's Reading examination score.
- **Writing Score:** Student's Writing examination score.

#Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression
import pickle

df = pd.read_csv('exams.csv')


df

df.head()

df.iloc[25]

df.info()

df.dtypes

df.describe()

df.rename(columns={
    'race/ethnicity': 'race_ethnicity',
    'parental level of education': 'parental_level_of_education',
    'test preparation course': 'test_preparation_course',
    'math score': 'math_score',
    'reading score': 'reading_score',
    'writing score': 'writing_score'
}, inplace=True)

target_column_name = 'math_score'
categorical_features_renamed = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

"""#Exploratory Data Analysis

##Corelation Variable
"""

plt.figure(figsize=(10, 5))
sns.heatmap(df.select_dtypes(include=[np.number]).corr(), annot=True, cmap='coolwarm')
plt.title('Corelation Variable')
plt.savefig('Corelation Variable.png')

"""
Warmer colors (closer to **1.000**) represent a stronger positive correlation between variables.
Cooler colors (closer to **0.825** in this case, although the scale may extend to lower values) represent a weaker positive correlation, while still indicating a strong overall relationship between the variables.

*   math_score vs reading_score = 0.82 → Strong correlation, indicating that students who perform well in mathematics also tend to perform well in reading.

*   reading_score vs writing_score = 0.95 → Very strong correlation, indicating that reading and writing scores are highly related.

*   math_score vs writing_score = 0.81 → Strong correlation as well, but slightly lower than reading-writing.
The correlation analysis shows that mathematics, reading, and writing scores are strongly related to one another. The strongest correlation is observed between reading and writing scores, indicating that students who perform well in reading also tend to perform well in writing. Mathematics scores are also positively correlated with both reading and writing scores, although the relationships are slightly weaker than the correlation between reading and writing. Overall, all three academic performance indicators are positively associated and tend to improve together.

#Data Distribution

## Visualization
"""
plt.figure(figsize=(10, 6))
sns.histplot(df['math_score'], kde=True, bins=20, color='blue')
plt.title('Mathematics Score Distribution', fontsize=15)
plt.xlabel('Mathematics Score', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.grid(axis='y', linestyle='--')
plt.show()

"""Mathematics Score Distribution
The visualization shows that most students scored between **60 and 80** in Mathematics. The distribution is approximately bell-shaped, indicating that students' scores are fairly evenly distributed, with a slightly higher concentration of students achieving above-average scores. Only a small number of students obtained very low or very high marks. Overall, the results suggest that the majority of students demonstrate a good level of mathematics performance.
###Gender vs Mathematics Score Visualization
"""

plt.figure(figsize=(15,5))
sns.countplot(x='gender', data=df)
plt.title('Distribusion of gender')
plt.savefig('gender.png')

"""
The visualization shows that the number of male students is slightly higher than the number of female students. However, the difference is relatively small, indicating that the dataset is well-balanced across both genders. This balanced distribution ensures that gender-based analysis can be performed fairly without significant bias caused by unequal sample sizes.
"""

categorical_cols = ['gender']
for col in categorical_cols:
  plt.figure(figsize= (10,5))
  sns.countplot(x=col, hue='math_score', data=df)
  plt.title(f'{col} vs math_score')
  plt.savefig(f'{col} vs math_score.png')

"""The darker the color, the higher the mathematics score. For example, in the male group, we can see many bars with dark purple color (high scores) compared to the female group. Female students tend to have a slightly lower distribution of mathematics scores compared to male students.

###Visualization of race_ethnicity vs math_score
"""

plt.figure(figsize=(10,5))
sns.countplot(x='race_ethnicity', data=df)
plt.title('Distribusion of race_ethnicity')
plt.savefig('race_ethnicity.png')

"""
This chart illustrates the distribution of students across different race and ethnicity groups. Group C contains the highest number of students, followed by Group D and Group B. In contrast, Group E and Group A have comparatively fewer students. This indicates that a large proportion of the dataset belongs to Groups C and D, which may influence the analysis if race or ethnicity is considered as a contributing factor.
"""

categorical_cols = ['race_ethnicity']
for col in categorical_cols:
  plt.figure(figsize= (25,8))
  sns.countplot(x=col, hue='math_score', data=df)
  plt.title(f'{col} vs math_score')
  plt.savefig(f'{col} vs math_score.png')

"""The visualization shows that groups C and D tend to have higher mathematics scores compared to other groups, as indicated by the dominance of darker colors. In contrast, group A has a distribution of scores that is generally lower. This indicates a difference in mathematical performance across ethnic groups.

### Mathematics Score Distribution by Parental Level of Education
"""

plt.figure(figsize=(15,5))
sns.countplot(x='parental_level_of_education', data=df)
plt.title('Distribusion of parental_level_of_education')
plt.savefig('parental_level_of_education.png')

"""
The chart shows that most students' parents have completed high school, hold an associate's degree, or have attended some college. Only a small proportion of parents possess a bachelor's or master's degree. This indicates that the majority of students come from families with a moderate level of educational background, while relatively fewer students have parents with higher education qualifications.
"""

categorical_cols = ['parental_level_of_education']
for col in categorical_cols:
  plt.figure(figsize= (25,8))
  sns.countplot(x=col, hue='math_score', data=df)
  plt.title(f'{col} vs math_score')
  plt.savefig(f'{col} vs math_score.png')

"""
The chart indicates that students whose parents have higher educational qualifications, such as a bachelor's or master's degree, generally achieve higher mathematics scores. In contrast, students whose parents have only completed high school or a lower level of education tend to have lower score distributions. This suggests that parents' educational background may have a positive influence on their children's mathematics performance.

### Mathematics Score Distribution by Lunch Type
"""

plt.figure(figsize=(15,5))
sns.countplot(x='lunch', data=df)
plt.title('Distribusion of lunch')
plt.savefig('lunch.png')

"""
The chart shows that the majority of students receive a standard lunch, while the remaining students receive free or reduced-price lunch. This indicates that most students come from families with relatively stable economic conditions, whereas a smaller proportion of students receive financial assistance for school meals.
"""

categorical_cols = ['lunch']
for col in categorical_cols:
  plt.figure(figsize= (15,5))
  sns.countplot(x=col, hue='math_score', data=df)
  plt.title(f'{col} vs math_score')
  plt.savefig(f'{col} vs math_score.png')

"""
The chart shows that students with a standard lunch tend to have higher mathematics scores (darker colors) compared to students who receive free or reduced-price lunch, which are dominated by lighter colors. This suggests a possible relationship between economic status and academic achievement.

### Mathematics Score Distribution by Race/Ethnicity
"""

plt.figure(figsize=(15,5))
sns.countplot(x='test_preparation_course', data=df)
plt.title('Distribusion of test_preparation_course')
plt.savefig('test_preparation_course.png')

"""
The chart shows that a larger number of students did not participate in the test preparation course compared to those who completed it. This is evident from the significantly taller **"none"** bar than the **"completed"** bar. The result indicates that most students in the dataset did not receive additional test preparation before taking the examination.
"""

categorical_cols = ['test_preparation_course']
for col in categorical_cols:
  plt.figure(figsize= (15,5))
  sns.countplot(x=col, hue='math_score', data=df)
  plt.title(f'{col} vs math_score')
  plt.savefig(f'{col} vs math_score.png')

"""The graph indicates that students who completed the test preparation course generally achieved higher mathematics scores. This suggests that the course may have a positive impact on academic performance.

#Data Distribution

##Duplicate Data
"""

print(f"\nNumber of Duplicate Rows: {df.duplicated().sum()}")
df_cleaned = df.drop_duplicates()
print(f"Number of Rows After Removing Duplicates: {len(df_cleaned)}")

"""##Missing Values"""

missing_values = df_cleaned.isnull().sum()
percentage_missing = (missing_values / len(df_cleaned)) * 100
missing_data_info = pd.DataFrame({
    'missing_value': missing_values,
    'percentage_missing': percentage_missing
})
print("\nMissing Values Information:")
print(missing_data_info)

"""#Outlier"""

numeric_column = df.select_dtypes(include=['int64']).columns
fig, axs = plt.subplots(ncols=len(numeric_column), figsize=(4 * len(numeric_column), 5))


for i,  column in enumerate(numeric_column):
  sns.boxplot(y=df[column], ax=axs[i], whis=1.5)
  axs [i].set_title(f'Box Plot for {column}')
  axs [i].set_xlabel('')
  axs [i].set_ylabel('')

plt.tight_layout(pad=0.4, w_pad=0.5, h_pad=0.5)
plt.show()

"""#Processing Data

##Encoding
"""

df_before = df.copy()

encoders = {}
for col in ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']:
  encoders[col] = LabelEncoder()
  df[col] =  encoders[col].fit_transform(df[col])

print("Before Encoding: ")
print(df_before[['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']].head())

print("After Encoding: ")
print(df[['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']].head())

"""## Data Normalization"""

Numerical = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
print(df[Numerical].describe())

"""##Feature Engineering"""

scaler = StandardScaler()
df[Numerical] = scaler.fit_transform(df[Numerical])
print(df[Numerical].describe())

plt.figure(figsize=(14, 7))
plt.subplot(1, 2, 1)
sns.scatterplot(x='reading_score', y=target_column_name, data=df, hue='gender', palette='coolwarm', alpha=0.7)
plt.title('Mathematics Score vs Reading Score', fontsize=15)
plt.xlabel('Reading Score', fontsize=12)
plt.ylabel('Mathematics Score', fontsize=12)
plt.grid(True, linestyle='--')

plt.figure(figsize=(14, 7))
plt.subplot(1, 2, 2)
sns.scatterplot(x='writing_score', y=target_column_name, data=df, hue='gender', palette='coolwarm', alpha=0.7)
plt.title('Mathematics Score vs Writing Score', fontsize=15)
plt.xlabel('Writing Score', fontsize=12)
plt.ylabel('Mathematics Score', fontsize=12)
plt.grid(True, linestyle='--')
plt.show()

df.head()

"""# Modeling"""

print("\n--- Part 2: Classification Model (Mathematics Score Category Prediction) ---")
df_class = df_cleaned.copy()

bins = [0, 59, 79, 100]
labels = ['Low', 'Medium', 'High']
df_class['score_class'] = pd.cut(df_class['math_score'], bins=bins, labels=labels, include_lowest=True, right=True)

print("\nMathematics Score Class Distribution:")
print(df_class['score_class'].value_counts())

X_class_features = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
X_class = df_class[X_class_features]
y_class = df_class['score_class']

categorical_transformer_class = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', drop='first'))
])

preprocessor_class = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer_class, X_class_features)
    ])

rf_class_pipeline = Pipeline(steps=[('preprocessor', preprocessor_class),
                                    ('classifier', RandomForestClassifier(random_state=42))])

X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
    X_class, y_class, test_size=0.2, random_state=42, stratify=y_class # stratify penting untuk target kelas
)

print("\nTraining Classification Model (Random Forest for score_class)...")
rf_class_pipeline.fit(X_train_class, y_train_class)

y_pred_class = rf_class_pipeline.predict(X_test_class)

print("\nClassification Report for 'score_class':")
print(classification_report(y_test_class, y_pred_class))

cm_class = confusion_matrix(y_test_class, y_pred_class, labels=rf_class_pipeline.named_steps['classifier'].classes_)
disp_class = ConfusionMatrixDisplay(confusion_matrix=cm_class, display_labels=rf_class_pipeline.named_steps['classifier'].classes_)
disp_class.plot(cmap='Blues')
plt.title('Confusion Matrix for score_class')
plt.show()

try:
    feature_names_out = rf_class_pipeline.named_steps['preprocessor'].get_feature_names_out()
    importances_class = rf_class_pipeline.named_steps['classifier'].feature_importances_

    feature_importance_df = pd.DataFrame({'feature': feature_names_out, 'importance': importances_class})
    feature_importance_df = feature_importance_df.sort_values(by='importance', ascending=False)

    plt.figure(figsize=(10, 8))
    sns.barplot(x='importance', y='feature', data=feature_importance_df.head(15), palette='viridis')
    plt.title('Random Forest - Feature Importance for score_class')
    plt.xlabel("Feature Importance")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f"Unable to display feature importance: {e}")

print("\n--- Part 3: Classification Model (Pass/Fail Status Prediction) ---")
df_status = df_cleaned.copy()

df_status['status'] = df_status['math_score'].apply(lambda x: 'Pass' if x >= 60 else 'Fail')

print("\nPass/Fail Status Distribution:")
print(df_status['status'].value_counts())

X_status_features = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
X_status = df_status[X_status_features]
y_status = df_status['status']

rf_status_pipeline = Pipeline(steps=[('preprocessor', preprocessor_class),
                                     ('classifier', RandomForestClassifier(random_state=42))])

X_train_status, X_test_status, y_train_status, y_test_status = train_test_split(
    X_status, y_status, test_size=0.2, random_state=42, stratify=y_status
)

print("\nTraining Classification Model (Random Forest for pass/fail status)...")
rf_status_pipeline.fit(X_train_status, y_train_status)

y_pred_status = rf_status_pipeline.predict(X_test_status)

print("\nClassification Report for 'pass/fail status':")
target_names_status = sorted(y_status.unique())
print(classification_report(y_test_status, y_pred_status, target_names=target_names_status))

accuracy_status = accuracy_score(y_test_status, y_pred_status)
print(f"Pass/Fail Model Accuracy: {accuracy_status:.4f}")

cm_status = confusion_matrix(y_test_status, y_pred_status, labels=target_names_status)
disp_status = ConfusionMatrixDisplay(confusion_matrix=cm_status, display_labels=target_names_status)
disp_status.plot(cmap='Greens')
plt.title('Confusion Matrix for Pass/Fail Classification')
plt.show()

print("\n--- Part 4: Regression Model for Predicting Mathematics Score ---")
df_reg = df_cleaned.copy()

"""## Feature and Target Data"""

X_reg_categorical_features = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
X_reg_numerical_features = ['reading_score', 'writing_score']
X_reg = df_reg[X_reg_categorical_features + X_reg_numerical_features]
y_reg = df_reg['math_score']

preprocessor_reg = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), X_reg_categorical_features),
        ('num', StandardScaler(), X_reg_numerical_features)
    ],
    remainder='passthrough'
)

lr_reg_pipeline = Pipeline(steps=[('preprocessor', preprocessor_reg),
                                  ('regressor', LinearRegression())])

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

print("\nTraining Regression Model (Linear Regression for math_score)...")
lr_reg_pipeline.fit(X_train_reg, y_train_reg)

pickle.dump(lr_reg_pipeline, open("model.pkl", "wb"))

y_pred_reg_test = lr_reg_pipeline.predict(X_test_reg)

mse_reg = mean_squared_error(y_test_reg, y_pred_reg_test)
r2_reg = r2_score(y_test_reg, y_pred_reg_test)

print("\nEvaluasi Model Regresi pada Data Uji:")
print(f"Mean Squared Error (MSE): {mse_reg:.2f}")
print(f"R-squared (R2 Score): {r2_reg:.2f}")

results_reg_df = pd.DataFrame({'Actual Math Score': y_test_reg, 'Predicted Math Score': y_pred_reg_test})
results_reg_df['Predicted Math Score'] = results_reg_df['Predicted Math Score'].round(2)
print("\nSample Comparison: Actual vs Predicted Mathematics Scores (Test Regression Data – First 10 Records):")
print(results_reg_df.head(10).to_string())

print("\n--- Regression Model Testing with Dummy Data ---")
data_dummy_reg = pd.DataFrame({
    'gender': ['female', 'male'],
    'race_ethnicity': ['group C', 'group A'],
    'parental_level_of_education': ["bachelor's degree", 'high school'],
    'lunch': ['standard', 'free/reduced'],
    'test_preparation_course': ['none', 'completed'],
    'reading_score': [70, 55],
    'writing_score': [75, 50] 
})

print("\nDummy Data for Regression:")
print(data_dummy_reg.to_string())

dummy_predictions_reg = lr_reg_pipeline.predict(data_dummy_reg)
dummy_predictions_reg_rounded = [round(p, 2) for p in dummy_predictions_reg]

data_dummy_reg['Predicted Math Score'] = dummy_predictions_reg_rounded
print("\nRegression Prediction Results for Dummy Data:")
print(data_dummy_reg.to_string())
